import reflex as rx

# import components
from ..components.product_component import product_component


def product_panel() -> rx.Component:
    return rx.container(
        rx.flex(
            product_component("https://www.planetaelectronico.com/images/productos/tornillo-rosca-chapa-ta29x6-5-din7981-1-10691.jpeg",
                              "BA-00123", 15.3, "Tornillo muy copado que sirve para colgar cuadros de calidad", 1534534535.3),
            product_component("https://www.planetaelectronico.com/images/productos/tornillo-rosca-chapa-ta29x6-5-din7981-1-10691.jpeg",
                              "BA-00123", 15, "Tornillo muy copado que sirve para colgar cuadros de calidad", 153333.3),
            product_component("https://www.planetaelectronico.com/images/productos/tornillo-rosca-chapa-ta29x6-5-din7981-1-10691.jpeg",
                              "BA-00123", 15, "Tornillo muy copado que sirve para colgar cuadros de calidad", 15.3),
            product_component("https://www.planetaelectronico.com/images/productos/tornillo-rosca-chapa-ta29x6-5-din7981-1-10691.jpeg",
                              "BA-00123", 15, "Tornillo muy copado que sirve para colgar cuadros de calidad", 15.3),
            product_component("https://www.planetaelectronico.com/images/productos/tornillo-rosca-chapa-ta29x6-5-din7981-1-10691.jpeg",
                              "BA-00123", 15, "Tornillo muy copado que sirve para colgar cuadros de calidad", 15.3),
            product_component("https://www.planetaelectronico.com/images/productos/tornillo-rosca-chapa-ta29x6-5-din7981-1-10691.jpeg",
                              "BA-00123", 15, "Tornillo muy copado que sirve para colgar cuadros de calidad", 15.3),
            product_component("https://www.planetaelectronico.com/images/productos/tornillo-rosca-chapa-ta29x6-5-din7981-1-10691.jpeg",
                              "BA-00123", 15, "Tornillo muy copado que sirve para colgar cuadros de calidad", 15.3),
            product_component("https://www.planetaelectronico.com/images/productos/tornillo-rosca-chapa-ta29x6-5-din7981-1-10691.jpeg",
                              "BA-00123", 15, "Tornillo muy copado que sirve para colgar cuadros de calidad", 15.3),
            product_component("https://www.planetaelectronico.com/images/productos/tornillo-rosca-chapa-ta29x6-5-din7981-1-10691.jpeg",
                              "BA-00123", 15, "Tornillo muy copado que sirve para colgar cuadros de calidad", 15.3),
            product_component("https://www.planetaelectronico.com/images/productos/tornillo-rosca-chapa-ta29x6-5-din7981-1-10691.jpeg",
                              "BA-00123", 15, "Tornillo muy copado que sirve para colgar cuadros de calidad", 15.3),
            product_component("https://www.planetaelectronico.com/images/productos/tornillo-rosca-chapa-ta29x6-5-din7981-1-10691.jpeg",
                              "BA-00123", 15, "Tornillo muy copado que sirve para colgar cuadros de calidad", 15.3),
            product_component("https://www.planetaelectronico.com/images/productos/tornillo-rosca-chapa-ta29x6-5-din7981-1-10691.jpeg",
                              "BA-00123", 15, "Tornillo muy copado que sirve para colgar cuadros de calidad", 15.3),
            product_component("https://www.planetaelectronico.com/images/productos/tornillo-rosca-chapa-ta29x6-5-din7981-1-10691.jpeg",
                              "BA-00123", 15, "Tornillo muy copado que sirve para colgar cuadros de calidad", 15.3),
            product_component("https://www.planetaelectronico.com/images/productos/tornillo-rosca-chapa-ta29x6-5-din7981-1-10691.jpeg",
                              "BA-00123", 15, "Tornillo muy copado que sirve para colgar cuadros de calidad", 15.3),
            product_component("https://www.planetaelectronico.com/images/productos/tornillo-rosca-chapa-ta29x6-5-din7981-1-10691.jpeg",
                              "BA-00123", 15, "Tornillo muy copado que sirve para colgar cuadros de calidad", 15.3),
            product_component("https://www.planetaelectronico.com/images/productos/tornillo-rosca-chapa-ta29x6-5-din7981-1-10691.jpeg",
                              "BA-00123", 15, "Tornillo muy copado que sirve para colgar cuadros de calidad", 15.3),
            product_component("https://www.planetaelectronico.com/images/productos/tornillo-rosca-chapa-ta29x6-5-din7981-1-10691.jpeg",
                              "BA-00123", 15, "Tornillo muy copado que sirve para colgar cuadros de calidad", 15.3),
            product_component("https://www.planetaelectronico.com/images/productos/tornillo-rosca-chapa-ta29x6-5-din7981-1-10691.jpeg",
                              "BA-00123", 15, "Tornillo muy copado que sirve para colgar cuadros de calidad", 15.3),
            product_component("https://www.planetaelectronico.com/images/productos/tornillo-rosca-chapa-ta29x6-5-din7981-1-10691.jpeg",
                              "BA-00123", 15, "Tornillo muy copado que sirve para colgar cuadros de calidad", 15.3),
            product_component("https://www.planetaelectronico.com/images/productos/tornillo-rosca-chapa-ta29x6-5-din7981-1-10691.jpeg",
                              "BA-00123", 15, "Tornillo muy copado que sirve para colgar cuadros de calidad", 15.3),
            product_component("https://www.planetaelectronico.com/images/productos/tornillo-rosca-chapa-ta29x6-5-din7981-1-10691.jpeg",
                              "BA-00123", 15, "Tornillo muy copado que sirve para colgar cuadros de calidad", 15.3),
            product_component("https://www.planetaelectronico.com/images/productos/tornillo-rosca-chapa-ta29x6-5-din7981-1-10691.jpeg",
                              "BA-00123", 15, "Tornillo muy copado que sirve para colgar cuadros de calidad", 15.3),
            product_component("https://www.planetaelectronico.com/images/productos/tornillo-rosca-chapa-ta29x6-5-din7981-1-10691.jpeg",
                              "BA-00123", 15, "Tornillo muy copado que sirve para colgar cuadros de calidad", 15.3),
            product_component("https://www.planetaelectronico.com/images/productos/tornillo-rosca-chapa-ta29x6-5-din7981-1-10691.jpeg",
                              "BA-00123", 15, "Tornillo muy copado que sirve para colgar cuadros de calidad", 15.3),
            product_component("https://www.planetaelectronico.com/images/productos/tornillo-rosca-chapa-ta29x6-5-din7981-1-10691.jpeg",
                              "BA-00123", 15, "Tornillo muy copado que sirve para colgar cuadros de calidad", 15.3),
            product_component("https://www.planetaelectronico.com/images/productos/tornillo-rosca-chapa-ta29x6-5-din7981-1-10691.jpeg",
                              "BA-00123", 15, "Tornillo muy copado que sirve para colgar cuadros de calidad", 15.3),
            justify_content="center",
            wrap="wrap",
            gap=["0.25rem", "0.5rem", "0.75rem", "1rem", "1.25rem"],
        ),
        id="product_panel",
        max_w="100%",
        max_h=f"calc((10/11)*100vh - 1em)",
        padding_top="0.5rem",
        overflow_y="auto",
    )
