import reflex as rx

# import components
from ..components.product_item import product_item


def product_area() -> rx.Component:
    return rx.container(
        rx.flex(
            product_item("https://www.planetaelectronico.com/images/productos/tornillo-rosca-chapa-ta29x6-5-din7981-1-10691.jpeg",
                         "BA-00123", 15, "Tornillo muy copado que sirve para colgar cuadros de calidad", 1534534535.3),
            product_item("https://www.planetaelectronico.com/images/productos/tornillo-rosca-chapa-ta29x6-5-din7981-1-10691.jpeg",
                         "BA-00123", 15, "Tornillo muy copado que sirve para colgar cuadros de calidad", 153333.3),
            product_item("https://www.planetaelectronico.com/images/productos/tornillo-rosca-chapa-ta29x6-5-din7981-1-10691.jpeg",
                         "BA-00123", 15, "Tornillo muy copado que sirve para colgar cuadros de calidad", 15.3),
            product_item("https://www.planetaelectronico.com/images/productos/tornillo-rosca-chapa-ta29x6-5-din7981-1-10691.jpeg",
                         "BA-00123", 15, "Tornillo muy copado que sirve para colgar cuadros de calidad", 15.3),
            product_item("https://www.planetaelectronico.com/images/productos/tornillo-rosca-chapa-ta29x6-5-din7981-1-10691.jpeg",
                         "BA-00123", 15, "Tornillo muy copado que sirve para colgar cuadros de calidad", 15.3),
            product_item("https://www.planetaelectronico.com/images/productos/tornillo-rosca-chapa-ta29x6-5-din7981-1-10691.jpeg",
                         "BA-00123", 15, "Tornillo muy copado que sirve para colgar cuadros de calidad", 15.3),
            product_item("https://www.planetaelectronico.com/images/productos/tornillo-rosca-chapa-ta29x6-5-din7981-1-10691.jpeg",
                         "BA-00123", 15, "Tornillo muy copado que sirve para colgar cuadros de calidad", 15.3),
            product_item("https://www.planetaelectronico.com/images/productos/tornillo-rosca-chapa-ta29x6-5-din7981-1-10691.jpeg",
                         "BA-00123", 15, "Tornillo muy copado que sirve para colgar cuadros de calidad", 15.3),
            product_item("https://www.planetaelectronico.com/images/productos/tornillo-rosca-chapa-ta29x6-5-din7981-1-10691.jpeg",
                         "BA-00123", 15, "Tornillo muy copado que sirve para colgar cuadros de calidad", 15.3),
            product_item("https://www.planetaelectronico.com/images/productos/tornillo-rosca-chapa-ta29x6-5-din7981-1-10691.jpeg",
                         "BA-00123", 15, "Tornillo muy copado que sirve para colgar cuadros de calidad", 15.3),
            product_item("https://www.planetaelectronico.com/images/productos/tornillo-rosca-chapa-ta29x6-5-din7981-1-10691.jpeg",
                         "BA-00123", 15, "Tornillo muy copado que sirve para colgar cuadros de calidad", 15.3),
            product_item("https://www.planetaelectronico.com/images/productos/tornillo-rosca-chapa-ta29x6-5-din7981-1-10691.jpeg",
                         "BA-00123", 15, "Tornillo muy copado que sirve para colgar cuadros de calidad", 15.3),
            product_item("https://www.planetaelectronico.com/images/productos/tornillo-rosca-chapa-ta29x6-5-din7981-1-10691.jpeg",
                         "BA-00123", 15, "Tornillo muy copado que sirve para colgar cuadros de calidad", 15.3),
            product_item("https://www.planetaelectronico.com/images/productos/tornillo-rosca-chapa-ta29x6-5-din7981-1-10691.jpeg",
                         "BA-00123", 15, "Tornillo muy copado que sirve para colgar cuadros de calidad", 15.3),
            product_item("https://www.planetaelectronico.com/images/productos/tornillo-rosca-chapa-ta29x6-5-din7981-1-10691.jpeg",
                         "BA-00123", 15, "Tornillo muy copado que sirve para colgar cuadros de calidad", 15.3),
            product_item("https://www.planetaelectronico.com/images/productos/tornillo-rosca-chapa-ta29x6-5-din7981-1-10691.jpeg",
                         "BA-00123", 15, "Tornillo muy copado que sirve para colgar cuadros de calidad", 15.3),
            product_item("https://www.planetaelectronico.com/images/productos/tornillo-rosca-chapa-ta29x6-5-din7981-1-10691.jpeg",
                         "BA-00123", 15, "Tornillo muy copado que sirve para colgar cuadros de calidad", 15.3),
            product_item("https://www.planetaelectronico.com/images/productos/tornillo-rosca-chapa-ta29x6-5-din7981-1-10691.jpeg",
                         "BA-00123", 15, "Tornillo muy copado que sirve para colgar cuadros de calidad", 15.3),
            product_item("https://www.planetaelectronico.com/images/productos/tornillo-rosca-chapa-ta29x6-5-din7981-1-10691.jpeg",
                         "BA-00123", 15, "Tornillo muy copado que sirve para colgar cuadros de calidad", 15.3),
            product_item("https://www.planetaelectronico.com/images/productos/tornillo-rosca-chapa-ta29x6-5-din7981-1-10691.jpeg",
                         "BA-00123", 15, "Tornillo muy copado que sirve para colgar cuadros de calidad", 15.3),
            product_item("https://www.planetaelectronico.com/images/productos/tornillo-rosca-chapa-ta29x6-5-din7981-1-10691.jpeg",
                         "BA-00123", 15, "Tornillo muy copado que sirve para colgar cuadros de calidad", 15.3),
            product_item("https://www.planetaelectronico.com/images/productos/tornillo-rosca-chapa-ta29x6-5-din7981-1-10691.jpeg",
                         "BA-00123", 15, "Tornillo muy copado que sirve para colgar cuadros de calidad", 15.3),
            product_item("https://www.planetaelectronico.com/images/productos/tornillo-rosca-chapa-ta29x6-5-din7981-1-10691.jpeg",
                         "BA-00123", 15, "Tornillo muy copado que sirve para colgar cuadros de calidad", 15.3),
            product_item("https://www.planetaelectronico.com/images/productos/tornillo-rosca-chapa-ta29x6-5-din7981-1-10691.jpeg",
                         "BA-00123", 15, "Tornillo muy copado que sirve para colgar cuadros de calidad", 15.3),
            product_item("https://www.planetaelectronico.com/images/productos/tornillo-rosca-chapa-ta29x6-5-din7981-1-10691.jpeg",
                         "BA-00123", 15, "Tornillo muy copado que sirve para colgar cuadros de calidad", 15.3),
            product_item("https://www.planetaelectronico.com/images/productos/tornillo-rosca-chapa-ta29x6-5-din7981-1-10691.jpeg",
                         "BA-00123", 15, "Tornillo muy copado que sirve para colgar cuadros de calidad", 15.3),
            justify_content="center",
            wrap="wrap",
            gap=["0.25rem", "0.5rem", "0.75rem", "1rem", "1.25rem"],
        ),
        max_w="100%",
        max_h=f"calc(100vh - {1/11}vh - 6rem)",
        padding_top="0.5rem",
        overflow_y="auto",
    )
